AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

Rails:
  Enabled: true

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/IndentHash:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/AlignHash:
  Enabled: true
  EnforcedLastArgumentHashStyle: always_ignore

Style/AsciiComments:
  Enabled: false

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
      inject: 'inject'

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - spec/**/*_spec.rb

Style/BracesAroundHashParameters:
  Exclude:
    - spec/**/*_spec.rb

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/SignalException:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 100

Metrics/ModuleLength:
  Max: 100

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Style/SingleLineBlockParams:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Style/FormatString:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true

Style/StringLiterals:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Naming/UncommunicativeMethodParamName:
  AllowedNames: [uf]

GlobalVars:
  AllowedVariables:
    - $redis
    - $rollout
